In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Regraun/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Regraun/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Regraun/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Regraun/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Regraun/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Regraun/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Regraun/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Regraun/anaconda3\\Library\\include']
Supported SIMD extensions in 

In [3]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
a=np.full(10,2.5)
print(a)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


In [6]:
python3 -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (3809857200.py, line 1)

In [7]:
a=np.zeros(10)
a[5]=1
print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [8]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
a=np.arange(1,5)
a=a[::-1]
print(a)

[4 3 2 1]


In [10]:
a=np.arange(0,9)
a=a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
a=[1,2,0,0,4,0]
b=np.nonzero(a)
print(b)

(array([0, 1, 4], dtype=int64),)


In [12]:
a=np.random.random((3,3,3))
print(a)

[[[0.17050887 0.08768477 0.79921833]
  [0.18880972 0.06313823 0.48069389]
  [0.57497793 0.58917586 0.46832222]]

 [[0.85070782 0.30715207 0.61888583]
  [0.76775009 0.85694856 0.49775063]
  [0.87531777 0.67887047 0.51994179]]

 [[0.6264255  0.4027034  0.99947219]
  [0.10977082 0.23235689 0.75218843]
  [0.43108225 0.7452744  0.46672968]]]


In [13]:
a=np.random.random((10, 10))
b=a.min()
c=a.max()
print("Minimum a = ", b)
print("Maximum a = ", c)

Minimum a =  0.008878201942054686
Maximum a =  0.9871683198119933


In [14]:
a=np.random.random(30)
b=a.mean()
print(b)

0.491634015428512


In [15]:
a=np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
0 * np.nan   
print(np.nan == np.nan)  
print(np.inf > np.nan)
print(np.nan - np.nan)

False
False
nan


In [17]:
a=np.zeros((5,5))
l=1
for i in range(5):
    for j in range(5):
        if i==j:
            a[i,j]=l
            l+=1
    
print(a)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [18]:
a=np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [19]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


In [20]:
a= np.tile(np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
